# Generated by Django 5.0.4 on 2025-02-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='wrench', max_length=50),
        ),
    ]
