# Generated by Django 5.0.4 on 2025-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('car', 'Voiture'), ('motorcycle', 'Moto'), ('truck', 'Camion'), ('van', 'Utilitaire')], default='car', max_length=20),
        ),
    ]
